name: From commands
on:
  push:
    branches: [master]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Init Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run liting
        run: |
          black ./src ./tests
          flake8 . --show-source --statistics
          isort src/ -rc
  testing:
    name: Testing
    needs: [linting]
    runs-on: ubuntu-latest
    steps:
      - name: Init Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run tests
        run: python -m pytest
